{{- if eq .Values.store.engine "woocommerce" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.store.name }}-db-secret
  labels:
    app: {{ .Values.store.name }}
    store.engine: {{ .Values.store.engine }}
type: Opaque
data:
  db-root-password: {{ default (randAlphaNum 16) .Values.woocommerce.db.rootPassword | b64enc | quote }}
  db-password: {{ default (randAlphaNum 16) .Values.woocommerce.db.password | b64enc | quote }}
  db-user: {{ default "wordpress" .Values.woocommerce.db.user | b64enc | quote }}
  db-name: {{ default "wordpress" .Values.woocommerce.db.name | b64enc | quote }}
{{- end }}
