apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.store.name }}-db-secret
  labels:
    app: {{ .Values.store.name }}
type: Opaque
stringData:
  mariadb-root-password: {{ .Values.woocommerce.db.rootPassword | quote }}
  mariadb-password: {{ .Values.woocommerce.db.password | quote }}
