apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.store.name }}
  labels:
    app: {{ .Values.store.name }}
    tier: frontend
    store.engine: {{ .Values.store.engine }}
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ .Values.store.name }}
    tier: frontend
