apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.store.name }}
  labels:
    app: {{ .Values.store.name }}
spec:
  ports:
    - port: 80
      targetPort: {{ if eq .Values.store.engine "woocommerce" }}80{{ else }}9000{{ end }}
      protocol: TCP
  selector:
    app: {{ .Values.store.name }}
    tier: frontend
